version: "3"
services:
  postgres:
    image: library/postgres:13
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 15s
      timeout: 15s
      retries: 2

  carsservice:
    image: registry.digitalocean.com/cfe-k8s-rsoi/carsservice
    build:
      context: lab2/carsservice
    container_name: carsservice
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATA_BASE_PORT: "5432"
      DATA_BASE_NAME: "postgres"
      DATA_BASE_USER: "postgres"
      DATA_BASE_PASS: "postgres"
      DATA_BASE_HOST: "postgres"
    ports:
      - "8070:8070"

  paymentservice:
    image: registry.digitalocean.com/cfe-k8s-rsoi/paymentservice
    build:
      context: lab2/paymentservice
    container_name: paymentservice
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATA_BASE_PORT: "5432"
      DATA_BASE_NAME: "postgres"
      DATA_BASE_USER: "postgres"
      DATA_BASE_PASS: "postgres"
      DATA_BASE_HOST: "postgres"
    ports:
      - "8050:8050"

  rentalservice:
    image: registry.digitalocean.com/cfe-k8s-rsoi/rentalservice
    build:
      context: lab2/rentalservice
    container_name: rentalservice
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATA_BASE_PORT: "5432"
      DATA_BASE_NAME: "postgres"
      DATA_BASE_USER: "postgres"
      DATA_BASE_PASS: "postgres"
      DATA_BASE_HOST: "postgres"
    ports:
      - "8060:8060"

  gatewayservice:
    image: registry.digitalocean.com/cfe-k8s-rsoi/gatewayservice
    build:
      context: lab2/gatewayservice
    container_name: gatewayservice
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATA_BASE_PORT: "5432"
      DATA_BASE_NAME: "postgres"
      DATA_BASE_USER: "postgres"
      DATA_BASE_PASS: "postgres"
      DATA_BASE_HOST: "postgres"
      CARS_SERVICE_HOST: "carsservice"
      CARS_SERVICE_PORT: "8070"
      PAYMENT_SERVICE_HOST: "paymentservice"
      PAYMENT_SERVICE_PORT: "8050"
      RENTAL_SERVICE_HOST: "rentalservice"
      RENTAL_SERVICE_PORT: "8060"

    ports:
      - "8080:8080"

volumes:
  db-data:
