version: "3"
services:
  postgres:
    image: library/postgres:13
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"

  gateway:
    image: registry.digitalocean.com/cfe-k8s-rsoi/gateway
    build: gateway/
    ports:
      - "8080:8080"
    depends_on:
      - cars
      - rental
      - payment

  cars:
    image: registry.digitalocean.com/cfe-k8s-rsoi/cars
    build: cars/
    ports:
      - "8070:8070"
    depends_on:
      - postgres

  rental:
    image: registry.digitalocean.com/cfe-k8s-rsoi/rental
    build: rental/
    ports:
      - "8060:8060"
    depends_on:
      - postgres

  payment:
    image: registry.digitalocean.com/cfe-k8s-rsoi/payment
    build: payment/
    ports:
      - "8050:8050"
    depends_on:
      - postgres

volumes:
  db-data:
