name: GitHub Classroom Workflow
on:
  push:
    branches: [ main ]
jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: docker/setup-buildx-action@v2
      - name: Build Images
        run: docker compose build
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_API_TOKEN_KEY }}
      - name: Login to docker container registry
        run: doctl registry login --expiry-seconds 1200
      - name: Push image in to Digital ocean Container Registry
        run: docker compose push
      - name: k8s cluster kubeconfig
        run: |
          doctl kubernetes cluster kubeconfig save --expiry-seconds 1200 rsoi-cluster
      - name: Deployment to the cluster
        run: |
          cd k8s
          helm upgrade --install postgres postgres-chart/
          helm upgrade --install services services-chart/
          sleep 120

      # TODO build, publish to docker hub, deploy to k8s

      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          collection: v3/postman/collection.json
          environment: v3/postman/environment.json
          delayRequest: 100
          reporters: '[ "cli" ]'

      - uses: education/autograding@v1
        id: autograder
        continue-on-error: true

      - name: Github auto grader mark
        uses: Romanow/google-sheet-autograder-marker@v1.0
        with:
          google_token: ${{secrets.GOOGLE_API_KEY}}
          sheet_id: "1xkgjUX6Qmk7rdJG-QPOToav-HWWtthJjnShIKnw3oIY"
          homework_number: 4
          user_column: 'D'
          column_offset: 'F'
          mark: "'+"
