name: GitHub Classroom Workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Login in dockerhub
        uses: docker/login-action@v2
        with:
          username: sohaibssb
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        uses: stCarolas/setup-maven@v4.4
        with:
          maven-version: 3.6.3
      - name: cars build
        run: mvn -f cars/pom.xml --batch-mode --update-snapshots clean install -DskipTests
      - name: payment build
        run: mvn -f payment/pom.xml --batch-mode --update-snapshots clean install -DskipTests
      - name: rental build
        run: mvn -f rental/pom.xml --batch-mode --update-snapshots clean install -DskipTests
      - name: gateway build
        run: mvn -f gateway/pom.xml --batch-mode --update-snapshots clean install -DskipTests

      - name: Build images
        run: |
          docker build ./rental/ -t sohaibssb/dockerhub:rental
          docker build ./payment/ -t sohaibssb/dockerhub:payment
          docker build ./cars/ -t sohaibssb/dockerhub:cars
          docker build ./gateway/ -t sohaibssb/dockerhub:gateway

      - name: Push docker images
        run: |
          docker push sohaibssb/dockerhub:rental
          docker push sohaibssb/dockerhub:payment
          docker push sohaibssb/dockerhub:cars
          docker push sohaibssb/dockerhub:gateway
          sleep 30
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_API_TOKEN_KEY }}
      - name: Login to docker container registry
        run: doctl registry login --expiry-seconds 1200
      - name: k8s cluster kubeconfig
        run: |
          doctl kubernetes cluster kubeconfig save --expiry-seconds 1200 rsoi-cluster
      - name: Deployment to the cluster
        run: |
          cd k8s
          helm uninstall postgres
          helm uninstall services
          sleep 120
          helm upgrade --install postgres postgres-chart/
          helm upgrade --install services services-chart/
          sleep 120

      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          collection: info/variants/v3/postman/collection.json
          environment: info/variants/v3/postman/environment.json
          delayRequest: 100
          reporters: '[ "cli" ]'

      - name: Dump docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v2
        with:
          images: 'library/postgres:13,gateway,rental,payment,cars'
          tail: '250'

      - uses: education/autograding@v1
        id: autograder
        continue-on-error: true

      - name: Github auto grader mark
        uses: Romanow/google-sheet-autograder-marker@v1.0
        with:
          google_token: ${{secrets.GOOGLE_API_KEY}}
          sheet_id: "1xkgjUX6Qmk7rdJG-QPOToav-HWWtthJjnShIKnw3oIY"
          homework_number: 4
          user_column: 'D'
          column_offset: 'F'
          mark: "'+"
